### PR TITLE
inject text embedding size in Imagen class as parameter

### PR DESCRIPTION
**Pull request by kapi-ai**

### CODE REVIEW

**Comment by kapi-ai** [comment]
There is a mismatch in the parameters supplied to UNet and Imagen. While you can change the size of the text embeddings in the UNet, it is hardcoded in Imagen. Both need to be changed, if you want to use an encoder with a different size as T5.

**Comment by lucidrains** [comment]
or does it not work?

**Comment by lucidrains** [comment]
@kapi-ai regardless i can make it overridable, but ideally someone does not even have to worry about the embedding dimensions for text by T5, just the T5 name

**Comment by lucidrains** [comment]
@kapi-ai in fact, the `Imagen` class will automatically override the `Unets` with the correct text embedding dimensions, depending on the t5_encoder_name that is given

**Comment by kapi-ai** [comment]
Thank you for your comments. 
For now, I will retract the PR, tbh, I think it was a bit premature because I literally just saw the mismatch while reading the code and made the PR. I will check, if other places need to be changed as well, maybe write a unit test for it to make sure I don't break anything.

> @kapi-ai ohh, but i think it should be able to fetch the correct `text_embed_dim` for you as long as you supply the correct t5 identifier (for huggingface) https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/t5.py#L37

Yes, that's true. The use-case here is to be independent of T5 as an text encoder to be able to user other encoders with different embedding dimensions as well (e.g. Clip or CoCa for image embedding or GPT/PaLM for text embedding). I, for example, wanted to condition Imagen on Clip instead of T5 embeddings to see if it works as well and what the differences are.

**Comment by kapi-ai** [comment]
Thanks for already pulling in the commit into master, I didn't check it before closing the PR!

**Pull request closed without merging**
