### PR TITLE
Optionally include intermediate images

### PR DESCRIPTION
**Pull request by Netruk44**
When generating images, it's sometimes useful to display the progression of images as generated by each unet in the cascade. This change adds an argument to `sample`: `include_intermediate_images` that optionally allows for the return to include the images generated by each network in the cascade.

### CODE REVIEW

**Comment by Netruk44** [comment]
I found this useful for personal use, and thought I would offer it back upstream. Feel free to close if you're not interested :)

**Comment by deepglugs** [comment]
+1

**Comment by lucidrains** [comment]
@Netruk44 hey, thanks for doing this! so i'm wondering why resize the earlier unet outputs to be the size of the last unet output? we could probably just keep them separate?

**Comment by Netruk44** [comment]
They had to be resized in order to be stacked (for my personal usage this was desired, but I can see that probably doesn't generalize lol), I can return an array instead.

**Review by lucidrains — APPROVED** [review]

**Pull request merged**
