### PR TITLE
Bug Fix: Accelerator scaler set after Accelerator.__init__()

### PR DESCRIPTION
**Pull request by gauenk**
The "optimizer.py" script in `accelerate` has more variables that must be set if "scaler" is not set to None. I just copied the init function directly from the accelerate code-base ([link here](https://github.com/huggingface/accelerate/blob/956114ac92cfbdfe0874ca73aa37ac815326f040/src/accelerate/optimizer.py#L63)). This allowed me to run the training example in the README. 

My guess is the `accelerate` package has simply been updated. This PR is merely to keep pace with the dependency.

### CODE REVIEW

**Comment by lucidrains** [comment]
@gauenk oh thanks Kent! yea i haven't kept up with accelerate updates

should probably pin the dep on a working version after merging this

**Comment by lucidrains** [comment]
@gauenk which version of accelerate did you get it working for btw? i think i'll just pin it from here on out

**Comment by gauenk** [comment]
My accelerate version is 0.23.0. Sorry for the delay -- I didn't see the message.

**Comment by lucidrains** [comment]
@gauenk no problem!

**Pull request merged**
